create database hotel;
use hotel;

/* Table 1: dim_date
Column Description for dim_date:
1. date: This column represents the dates present in May, June and July.
2. mmm yy: This column represents the date in the format of mmm yy (monthname year).
3. week no: This column represents the unique week number for that particular date.
4. day_type: This column represents whether the given day is Weekend or Weekeday.*/

SELECT * FROM dim_date; 

select distinct(`mmm yy`) from dim_date; # The data consist of 3months i.e., May, June And July for the year 2022

/* Table 2: dim_hotels
Column Description for dim_hotels:
1. property_id: This column represents the Unique ID for each of the hotels.
2. property_name: This column represents the name of each hotel.
3. category: This column determines which class[Luxury, Business] a particular hotel/property belongs to. 
4. city: This column represents where the particular hotel/property resides in.*/

select * from dim_hotels;
select count(distinct(property_id))
from dim_hotels;         # Data contain total 25 unique property/hotel

select distinct(category) from dim_hotels;  # 2 categories- Luxury & Business
select distinct(city) from dim_hotels;    # Hotels spread across 4 cities- Delhi, Mumbai, Hyderabad, Bangalore

/* Table 3- dim_rooms

Column Description for dim_rooms:
1. room_id: This column represents the type of room[RT1, RT2, RT3, RT4] in a hotel.
2. room_class: This column represents to which class[Standard, Elite, Premium, Presidential] particular room type belongs. */

select * from dim_rooms;  

/* Table 4 - fact_aggregated_bookings

Column Description for fact_aggregated_bookings:
1. property_id: This column represents the Unique ID for each of the hotels.
2. check_in_date: This column represents all the check_in_dates of the customers.
3. room_category: This column represents the type of room[RT1, RT2, RT3, RT4] in a hotel.
4. successful_bookings: This column represents all the successful room bookings that happen for a particular room type in that hotel on that particular date.
5. capacity: This column represents the maximum count of rooms available for a particular room type in that hotel on that particular date. */

select * from fact_aggregated_bookings;  # This table is showing no. of room bookings on a particular date for particular room of a hotel.

# Lets check the total capacity
select sum(capacity) from fact_aggregated_bookings;   # Total 2,32,576 rooms are available under Atliq Grand Hotels

/* Table 5- fact_bookings

Column Description for fact_bookings:
1. booking_id: This column represents the Unique Booking ID for each customer when they booked their rooms.
2. property_id: This column represents the Unique ID for each of the hotels
3. booking_date: This column represents the date on which the customer booked their rooms.
4. check_in_date: This column represents the date on which the customer check-in(entered) at the hotel.
5. check_out_date: This column represents the date on which the customer check-out(left) of the hotel.
6. no_guests: This column represents the number of guests who stayed in a particular room in that hotel.
7. room_category: This column represents the type of room[RT1, RT2, RT3, RT4] in a hotel.
8. booking_platform: This column represents in which way the customer booked his room.
9. ratings_given: This column represents the ratings given by the customer for hotel services.
10. booking_status: This column represents whether the customer cancelled his booking[Cancelled], successfully stayed in the hotel[Checked Out] or booked his room but not stayed in the hotel[No show].
11. revenue_generated: This column represents the amount of money generated by the hotel from a particular customer.
12. revenue_realized: This column represents the final amount of money that goes to the hotel based on booking status. If the booking status is cancelled, then 40% of the revenue generated is deducted and the remaining is refunded to the customer. If the booking status is Checked Out/No show, then full revenue generated will goes to hotels.
*/

select * from fact_bookings;
# Lets check the unique booking platforms
select distinct(booking_platform) from fact_bookings;    # 7 booking platforms - direct online, logtrip, tripster, makeyourtrip, journey,direct offline, others

# Now lets check the booking status
select count(booking_status) as 'total successfull booking'
from fact_bookings where booking_status='Checked Out';    # Out of 125863 bookings, 94411 no. of bookings where customer stayed successfully.

select count(booking_status)*100 / (select count(*) from fact_bookings) as 'successfull_booking_%'
from fact_bookings where booking_status='Checked Out';      # 70.14 % successfull booking where customer actualy stayed.

select count(*)*100 / (select count(*) from fact_bookings) as 'Cancelled_booking_%'
from fact_bookings where booking_status='Cancelled';        # 24.83 % cancelled their booking

select count(*)*100 / (select count(*) from fact_bookings) as 'No_Show%'
from fact_bookings where booking_status='No Show';         # 5.02% customers did not show after booking

# Lets check the total Revenue generated in 3 month
select sum(revenue_realized) from fact_bookings;   # Rs. 170.87 Crore revenue generated by AtliQ grand hotels in 3 months

# Lets find out the OCCUPANY % (no. of rooms ocuupied/ total no. of rooms)

SELECT sum(successful_bookings) * 100.0 / SUM(capacity) AS 'occupancy %'
FROM fact_aggregated_bookings;                  # 57.86% occupancy

# Lets find out average rating given by customers

select avg(ratings_given) as 'Average_Rating'
from fact_bookings
where ratings_given is not null AND ratings_given <> '';    # After considering only those customers who gave ratings, the average rating came out as 3.61


# Lets check the contribution from each Booking Platform

select booking_platform, count(booking_status) as 'No. of Bookings', 
count(booking_status)*100/(select count(*) from fact_bookings) as 'Booking % based on Platform'
from fact_bookings
group by booking_platform
order by count(booking_status) desc;     # other platform constitute highest booking % of 40.91% , foolowed by makeyourtrip with 19.98%


# lets find the booking % by type of Rooms
select a.room_id, a.room_class, count(b.booking_status) as 'No. of booking',
count(b.booking_status)*100/ (select count(*) from fact_bookings) as 'Booking %  based on Room Category'
from dim_rooms a
join fact_bookings b
on a.room_id=b.room_category
group by a.room_id, a.room_class
order by count(b.booking_status) desc;    # max booking 5 is for Elite CAtegory with 36.78%, followed by Standard with 28.56%.

# Lets find the Average Daily Rate (ADR)
# ADR= Total room revenue/ Total room sold -It provides insight into the average price paid by guests for rooms sold during a specific period

select sum(revenue_realized)/ count(distinct booking_id)
from fact_bookings;     # ADR is Rs. 12.69K per room. i.e, on average, each room sold during that day generated Rs.12.69K in revenue.

# Lets find out the Revenue Per Available Room (RevPAR)
select sum(a.revenue_realized)/ sum(b.capacity) as 'Revenue Per Available Room'
from fact_bookings a
join fact_aggregated_bookings b
on a.property_id=b.property_id; 

